version: '3.3'

services:
  db:
    container_name: test-constructor-bot
    image: postgres:14.1-alpine
    env_file:
      - ".env"
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
